apiVersion: v1
kind: Service
metadata:
  name: choremaster-app
  labels:
    app: {{ .Chart.Name }}
    component: app
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: {{ .Chart.Name }}
    component: app
