{{- if .Values.backend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: choremaster-backend
  labels:
    app: {{ .Chart.Name }}
    component: backend
spec:
  type: {{ .Values.backend.service.type }}
  ports:
  - port: {{ .Values.backend.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: {{ .Chart.Name }}
    component: backend
{{- end }}
