apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: choremaster-postgresql-pvc
  labels:
    app: {{ .Chart.Name }}
    component: postgresql
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.postgresql.persistence.storageClass }}
  storageClassName: {{ .Values.postgresql.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.postgresql.persistence.size }}
