apiVersion: v1
kind: Service
metadata:
  name: choremaster-postgresql
  labels:
    app: {{ .Chart.Name }}
    component: postgresql
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.postgresql.service.port }}
    targetPort: postgresql
    protocol: TCP
    name: postgresql
  selector:
    app: {{ .Chart.Name }}
    component: postgresql