apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: choremaster-postgresql-pvc
  labels:
    app: {{ .Chart.Name }}
    component: postgresql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgresql.database.size }}
