apiVersion: v1
kind: Secret
metadata:
  name: choremaster-postgresql-secret
  labels:
    app: {{ .Chart.Name }}
    component: postgresql
type: Opaque
stringData:
  username: postgres
  password: postgres
